apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-app
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk
  username: c3R1ZGVudF91c2Vy
  password: c3R1ZGVudF9wYXNz
  database: c3R1ZGVudF9kYg==
